name: ShadowDimensions
main: shadowlord.dimensions.ShadowDimensions
version: "1.0.0"
api-version: 1.12
authors: [shadowlord]
commands:
  dimension:
    description: Manage custom dimensions and portals
    usage: /dimension <create|list|info|regen|wand|setportal|removeportal> [...]
permissions:
  shadowdimensions.use:
    description: Basic use of dimension commands
    default: op
  shadowdimensions.admin:
    description: Admin actions for dimensions and portals
    default: op
  shadowdimensions.wand:
    description: Receive and use portal selector wand
    default: op
